version: "3.4"

services:
  app:
    image: express-graphql:${VERSION:-latest}
    build:
      dockerfile: ./Dockerfile
      context: .

  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
